### ISSUE TITLE
Hello! I had some questions about your scripts

### ISSUE THREAD

**Issue by biggs420** [Boyos999/Boyos-Tes3mp-Scripts#3]
Hi so about your randomness helper and dungeon loot will the scripts honor itemleveled lists if entries are put in to the json table or will it just pull any random peice out disregarding levelled lists?

**Comment by Boyos999** [comment]
**Short answer:** Unfortunately leveled lists do not work with the dungeon loot script.

**Long answer:** I believe this is because leveled lists are turned into items (when the actual roll is done) when a player loads the cell, and since items in the tables for dungeon aren't "loaded" in a cell rather than getting an item added to the player's inventory, they would get a leveled list added to their inventory, which does nothing (I've tested this).

Without access to game data on the server side the only way to deal with this would be to populate several json tables with the contents of each leveled list, and recursively choose an item from one of them to add to the player. Basically you'd have to replicate leveled list functionality in a script and have copies of all leveled lists on the server.
